[phases.setup]
nixPkgs = ["curl", "unzip"]
cmds = ["curl -fsSL https://bun.sh/install | bash"]

[phases.install]
cmds = ["rm package.json && bun add elysia @elysiajs/cors"]

[phases.build]
cmds = ["bun run build:ws"]

[start]
cmd = "bun run start:ws"
