[variables]
NIXPACKS_NODE_VERSION = "26"

[phases.setup]
nixPkgs = ["curl", "unzip"]
cmds = ["curl -fsSL https://bun.sh/install | bash"]

[phases.install]
cmds = ["npm install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build:ws"]

[start]
cmd = "bun run start:ws"
