allowBuilds:
  '@prisma/engines': true
  msw: set this to true or false
  prisma: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - sonner@2.0.8
overrides:
  zod: ^3.25.76
